SocketDescriptor: Support rvalue references
The following compilation error on mingw32 is fixed by this patch:

"  CXX     output/PC/./src/Device/Port/SocketPort.o"
./src/Device/Port/SocketPort.cpp: In member function 'void SocketPort::Set(
SocketDescriptor&&)':
./src/Device/Port/SocketPort.cpp:72:29: error: use of deleted function 'Soc
ketDescriptor& SocketDescriptor::operator=(const SocketDescriptor&)'
In file included from ./src/Device/Port/SocketPort.hpp:28:0,
                 from ./src/Device/Port/SocketPort.cpp:24:
./src/OS/SocketDescriptor.hpp:41:7: note: 'SocketDescriptor& SocketDescript
or::operator=(const SocketDescriptor&)' is implicitly deleted because the d
efault definition would be ill-formed:
./src/OS/SocketDescriptor.hpp:41:7: error: use of deleted function 'FileDes
criptor& FileDescriptor::operator=(const FileDescriptor&)'
In file included from ./src/OS/SocketDescriptor.hpp:33:0,
                 from ./src/Device/Port/SocketPort.hpp:28,
                 from ./src/Device/Port/SocketPort.cpp:24:
./src/OS/FileDescriptor.hpp:44:7: note: 'FileDescriptor& FileDescriptor::op
erator=(const FileDescriptor&)' is implicitly declared as deleted because '
FileDescriptor' declares a move constructor or move assignment operator
mingw32-make: *** [output/PC/./src/Device/Port/SocketPort.o] Error 1