SocketDescriptor: Cast Get() output to unsigned for winsock.h
On Windows the winsock.h expects a SOCKET as the first parameter of FD_SET
and the same header typedefs SOCKET as unsigned int. If the output of Get()
is passed directly as an int, then the following error appears on mingw32:

./src/OS/SocketDescriptor.cpp: In member function 'int SocketDescriptor::Wa
itReadable(int) const':
./src/OS/SocketDescriptor.cpp:193:3: error: comparison between signed and u
nsigned integer expressions [-Werror=sign-compare]
./src/OS/SocketDescriptor.cpp: In member function 'int SocketDescriptor::Wa
itWritable(int) const':
./src/OS/SocketDescriptor.cpp:212:3: error: comparison between signed and u
nsigned integer expressions [-Werror=sign-compare]
cc1plus.exe: all warnings being treated as errors
mingw32-make: *** [output/PC/./src/OS/SocketDescriptor.o] Error 1